name: Firt workflow

on:
  push:
    branches:
      - main
      - develop
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: build project
        run: echo "compilando proyecto."

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: test project
        run: echo "test"        