name: Firt workflow

# on:
#   push:
#     branches:
#       - main
#       - develop
#       - release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Valor env'
        required: false            
      dotnet-version-input:
        description: 'Version de .net'
        required: true
        default: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ github.event.inputs['dotnet-version-input'] }}

      - name: Ls
        run: ls

      - name: Restore
        run: dotnet restore

      - name: build
        run: dotnet build --no-restore --configuration Release

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: test project
        run: echo "test"        